version: '3'

services:
    jekyll:
      image: jekyll/jekyll:3.8.5
      container_name: laudams.net
      environment:
        - JEKYLL_ENV=docker
      command: jekyll serve --force_polling --livereload
      ports:
        - 4000:4000
      volumes:
        - ./:/srv/jekyll
